version: "3.2"
services:
  mock-premier-league:
    build: .
    ports:
      - "3710:3710"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env
    depends_on:
      - mongo-db
    links:
      - redis:redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

  redis:
    image: "redis:alpine"

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - db:/data/db

volumes:
  db:
  app:

